# Generated by Django 4.2.5 on 2023-10-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="author_photos/"),
        ),
    ]
